name: Data Deploy

on:
  push:
    paths:
      - data.json   # Trigger workflow jika ada perubahan pada data.json
    branches:
      - main        # Hanya berjalan pada branch main
  workflow_dispatch:  # Memungkinkan manual trigger dari tab Actions

permissions:
  contents: read   # Untuk membaca konten repositori
  pages: write     # Untuk melakukan deploy ke GitHub Pages
  id-token: write  # Untuk menggunakan token ID jika diperlukan

concurrency:
  group: "pages"
  cancel-in-progress: false  # Agar deployment yang sedang berjalan tidak dibatalkan

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Mengambil kode terbaru dari repositori

      - name: Deploy data.json to GitHub Pages
        run: |
          # Pastikan data.json ada dan siap untuk dideploy
          cp data.json ./_site/data.json  # Salin data.json ke folder _site untuk deploy ke GitHub Pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Deploy ke GitHub Pages
