name: Update Nonce and Deploy

on:
  schedule:
    - cron: '*/5 * * * *' # Jalankan setiap 5 menit
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run script to update HTML
      run: node sc.js

    - name: Debug file contents
      run: cat sc.js

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Stage all modified and minified files
        git add .
        
        # Check if there are any changes before committing
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update index.html and minified JS files with dynamic nonce"
          git push
        fi
