name: Update Nonce and Deploy

on:
  schedule:
    - cron: '*/5 * * * *' # Menjalankan setiap 5 menit
  push:
    branches:
      - main

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Clear Node.js Cache and Install Dependencies
      run: |
        # Hapus cache Node.js dan node_modules
        npm cache clean --force
        rm -rf node_modules package-lock.json
        
        # Instal ulang dependensi
        npm install html-minifier@4.0.0 source-map@0.7.4 clean-css@5.2.4

    - name: Debug installed modules
      run: |
        ls -l node_modules/
        ls -l node_modules/source-map/

    - name: Run script to update HTML
      run: node sc.js

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Stage all modified files
        git add .
        
        # Check if there are any changes before committing
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update index.html with dynamic nonce"
          git push
        fi
